class Largest{
    constructor(numeros){
        this.numeros=numeros
    }
}
var hola="slbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddslbfhsdfasdfjsdfohasdfoiahsdfshdfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
console.log(Number.MAX_SAFE_INTEGER);  


